# Generated by Django 4.2.3 on 2023-07-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('public_private', models.CharField(max_length=100)),
                ('research_class', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=1500)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='trackr_app.state')),
            ],
        ),
    ]
